MODE = "DEV"

VIDEO_DURATION = 30
FINAL_HOLD_SECONDS = 5
FPS = 20
TOTAL_FRAMES = VIDEO_DURATION * FPS

WINDOW_WIDTH = 854
WINDOW_HEIGHT = 480

CAMERA_HEIGHT = 1400
CAMERA_DISTANCE = 2800
LOOK_AHEAD = 260
CAMERA_SMOOTHING = 30
FOCAL_HEIGHT = 220

TRACK_RADIUS = 7
TRACK_SIDES = 8

TRACE_PROGRESSIVE = True
TRACE_UPDATE_EVERY = 15

USE_SATELLITE = False

PROJECT_TITLE = "GPX Flyover Studio"