MODE = "DEV"

VIDEO_DURATION = 30
FINAL_HOLD_SECONDS = 5
FPS = 20
TOTAL_FRAMES = VIDEO_DURATION * FPS

WINDOW_WIDTH = 854
WINDOW_HEIGHT = 480

CAMERA_MODE = "flyover"
CAMERA_PRESET = "cinematic"

CAMERA_HEIGHT = 1700
CAMERA_DISTANCE = 3600
LOOK_AHEAD = 420
CAMERA_SMOOTHING = 45
FOCAL_HEIGHT = 260
SIDE_OFFSET = 450

CAMERA_ORIENTATION_MODE = "route"
CAMERA_ORIENTATION_ANGLE = 0.0

TRACK_RADIUS = 7
TRACK_SIDES = 8
TRACK_RENDER_MODE = "line"

TRACE_PROGRESSIVE = True
TRACE_UPDATE_EVERY = 5

LEADER_ENABLED = True
LEADER_STYLE = "glow"
LEADER_RADIUS = 20.0
LEADER_Z_OFFSET = 18.0
LEADER_COLOR = "#FC4C02"
LEADER_HALO_SCALE = 1.8
LEADER_HALO_OPACITY = 0.20

LEADER_SCREEN_SPACE_ENABLED = True
LEADER_REFERENCE_DISTANCE = 2000
LEADER_MINIMUM_SCALE = 0.45
LEADER_MAXIMUM_SCALE = 4.0

LEADER_TRAIL_ENABLED = True
LEADER_TRAIL_FRACTION = 0.035
LEADER_TRAIL_WIDTH = 10.0
LEADER_TRAIL_OPACITY = 0.55
LEADER_TRAIL_UPDATE_EVERY = 2

PREDICTIVE_CAMERA_ENABLED = True

PREDICTIVE_MIN_LOOK_AHEAD = 120
PREDICTIVE_MAX_LOOK_AHEAD = 850
PREDICTIVE_ANALYSIS_WINDOW = 100

PREDICTIVE_CURVATURE_STRENGTH = 0.75
PREDICTIVE_SLOPE_STRENGTH = 1.0
PREDICTIVE_RELIEF_STRENGTH = 0.65

PREDICTIVE_POSITION_SMOOTHING = 0.08
PREDICTIVE_FOCAL_SMOOTHING = 0.10

USE_SATELLITE = True

TIMELINE = []

PROJECT_TITLE = "GPX Flyover Studio"