MODE = "DEV"

VIDEO_DURATION = 30
FINAL_HOLD_SECONDS = 5
FPS = 20
TOTAL_FRAMES = VIDEO_DURATION * FPS

WINDOW_WIDTH = 854
WINDOW_HEIGHT = 480

CAMERA_HEIGHT = 1700
CAMERA_DISTANCE = 3600
LOOK_AHEAD = 420
CAMERA_SMOOTHING = 45
FOCAL_HEIGHT = 260
SIDE_OFFSET = 450

TRACK_RADIUS = 7
TRACK_SIDES = 8
TRACK_RENDER_MODE = "line"  # "line" rapide ou "tube" qualité

TRACE_PROGRESSIVE = True
TRACE_UPDATE_EVERY = 10

USE_SATELLITE = False

TIMELINE = []

PROJECT_TITLE = "GPX Flyover Studio"