DEFAULT_CONFIG = {
    "project": {"title": "GPX Flyover Studio V5"},
    "gpx": {"file": ""},
    "camera": {
        "mode": "director",
        "orientation": "auto",
        "distance": {"min": 1200.0, "max": 3600.0, "scale": 0.40},
        "height": {"min": 600.0, "max": 1900.0, "scale": 0.20},
        "lateral": {"min": 160.0, "max": 700.0, "scale": 0.12},
        "look_ahead": 260,
        "smoothing": 0.10,
    },
    "track": {
        "color": "#FC4C02",
        "width": 1.5,
        "z_offset": 8.0,
        "progressive": True,
        "leader": False,
    },
    "terrain": {
        "source": "copernicus",
        "satellite": True,
        "satellite_zoom": 14,
        "max_cells": 60000,
        "margin": 0.006,
    },
    "timeline": {
        "intro": 2.0,
        "zoom_to_start": 2.0,
        "start_hold": 3.0,
        "travel": 30.0,
        "slowdown_start": 2.0,
        "slowdown_end": 3.0,
        "arrival_hold": 5.0,
        "flatten": 3.0,
        "profile_animation": 6.0,
        "profile_hold": 4.0,
        "fade_out": 2.0,
    },
    "video": {
        "fps": 20,
        "resolution": "1280x720",
        "output": "output/video/flyover_v5.mp4",
        "mode": "PREVIEW",
    },
}
